'use client';

import { startTransition, useEffect, useMemo, useState, type ReactNode } from 'react';
import Link from 'next/link';
import { mockMatch as baseMockMatch } from '@/app/data/mockMatch';
import { getTeamCrest } from '@/app/lib/teamCrests';

const mockMatch = { ...baseMockMatch, venue: { ...(<span>{baseMockMatch.venueName}</span>), ...baseMockMatch.venueInfo } };
const teams = [mockMatch.teams.atletico, mockMatch.teams.real] as const;
const navItems = ['Resumen', 'Estadísticas', 'Alineaciones', 'Táctica', 'H2H', 'Tabla', 'Noticias'];
const toneByResult = { W: 'border-emerald-400/40 bg-emerald-400/10 text-emerald-200', D: 'border-amber-400/40 bg-amber-400/10 text-amber-200', L: 'border-rose-400/40 bg-rose-400/10 text-rose-200' } as const;
const labels: Record<string, string> = { W: 'Victoria', D: 'Empate', L: 'Derrota' };

function formatCountdown(totalSeconds: number) {
  if (totalSeconds > 1_000_000) {
    return { days: '--', hours: '--', minutes: '--', seconds: '--' };
  }

  const safe = Math.floor(Math.max(totalSeconds, 0));
  return { days: Math.floor(safe / 86400), hours: Math.floor((safe % 86400) / 3600), minutes: Math.floor((safe % 3600) / 60), seconds: safe % 60 };
}

function Crest({ team, size = 'h-20 w-20' }: { team: { name: string; crest: string }; size?: string }) {
  return <div className={`flex ${size} shrink-0 items-center justify-center rounded-2xl border border-white/10 bg-slate-950/70 p-2`}><img src={team.crest || getTeamCrest(team.name)} alt={`Escudo de ${team.name}`} className="h-full w-full object-contain" /></div>;
}

function SectionTitle({ eyebrow, title, id }: { eyebrow: string; title: ReactNode; id?: string }) {
  return <div id={id} className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-cyan-300">{eyebrow}</p><h2 className="mt-2 font-editorial text-3xl text-white md:text-4xl">{title}</h2></div></div>;
}

function ComparativeBars({ items, keys }: { items: Array<{ label: string; values: [number, number]; suffix?: string }>; keys?: [string, string] }) {
  return <div className="grid gap-3 sm:grid-cols-2">{items.map((item) => { const difference = item.values[1] - item.values[0]; return <div key={item.label} className="rounded-xl border border-white/10 bg-white/[0.04] p-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500">{item.label}</p><div className="mt-3 grid grid-cols-[1fr_auto_1fr] items-end gap-2"><div><p className="text-[10px] text-cyan-200">{keys?.[0] ?? 'Local'}</p><p className="mt-1 text-2xl font-black text-white">{item.values[0]}{item.suffix ?? ''}</p></div><span className={`pb-1 text-xs font-bold ${difference > 0 ? 'text-amber-200' : difference < 0 ? 'text-cyan-200' : 'text-slate-500'}`}>{difference === 0 ? '=' : `${difference > 0 ? '+' : ''}${difference.toFixed(2)}`}</span><div className="text-right"><p className="text-[10px] text-amber-200">{keys?.[1] ?? 'Visitante'}</p><p className="mt-1 text-2xl font-black text-white">{item.values[1]}{item.suffix ?? ''}</p></div></div></div>; })}</div>;
}

function metricItems(section: 'attack' | 'defense', rows: Array<[string, string, string?]>) {
  const home = teams[0][section] as Record<string, number>;
  const away = teams[1][section] as Record<string, number>;
  return rows.map(([label, key, suffix]) => ({ label, values: [home[key], away[key]] as [number, number], suffix }));
}

function FormPanel({ team }: { team: typeof teams[number] }) {
  return <article className="photo-panel photo-form rounded-2xl p-5 md:p-7"><div className="relative z-10"><div className="flex items-center gap-3"><Crest team={team} size="h-12 w-12" /><div><h3 className="font-semibold text-white">{team.name}</h3><p className="text-xs text-slate-300">Últimos 5 partidos</p></div></div><div className="mt-5 flex gap-2">{team.form.map((result, index) => <span key={`${result}-${index}`} title={labels[result]} className={`flex h-9 w-9 items-center justify-center rounded-lg border text-xs font-black ${toneByResult[result]}`}>{result}</span>)}</div><div className="mt-5 space-y-3">{team.recentMatches.map((match) => <div key={`${match.opponent}-${match.score}`} className="flex items-center justify-between gap-3 border-b border-white/10 pb-2 text-sm last:border-0 last:pb-0"><span className="truncate text-slate-100">{match.venue === 'Local' ? 'vs' : '@'} {match.opponent}</span><span className="font-semibold text-white">{match.score}</span><span className={`text-xs font-bold ${match.result === 'W' ? 'text-emerald-300' : match.result === 'L' ? 'text-rose-300' : 'text-amber-300'}`}>{match.result}</span></div>)}</div></div></article>;
}

function Lineup({ team }: { team: typeof teams[number] }) {
  const [selected, setSelected] = useState<string | null>(null);
  return <article className="rounded-2xl border border-slate-800 bg-slate-950/70 p-4 md:p-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Crest team={team} size="h-11 w-11" /><div><h3 className="font-semibold text-white">{team.name}</h3><p className="text-xs text-cyan-300">{team.lineup.formation} · Alineación probable</p></div></div><span className="rounded-full border border-amber-400/30 bg-amber-400/10 px-2 py-1 text-[10px] font-bold text-amber-200">DEMO MOCK</span></div><div className="relative mt-5 aspect-[1.35/1] overflow-hidden rounded-xl border border-emerald-300/20 bg-[#123b32]" onMouseLeave={() => setSelected(null)}><div className="absolute inset-3 rounded-lg border border-white/25" /><div className="absolute left-1/2 top-1/2 h-px w-[calc(100%-1.5rem)] -translate-x-1/2 bg-white/20" /><div className="absolute left-1/2 top-1/2 h-16 w-16 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/20" />{team.lineup.players.map((player) => <button key={player.name} type="button" onMouseEnter={() => setSelected(player.name)} onFocus={() => setSelected(player.name)} className="absolute -translate-x-1/2 -translate-y-1/2 text-center" style={{ left: `${player.x}%`, top: `${player.y}%` }}><span className={`mx-auto flex h-8 w-8 items-center justify-center rounded-full border-2 text-[10px] font-bold text-white shadow-lg ${player.status === 'DUDA' ? 'border-amber-300 bg-amber-800' : 'border-cyan-200 bg-slate-900'}`}>{player.number}</span><span className="mt-1 block max-w-16 truncate text-[9px] font-semibold text-white">{player.name}</span></button>)}{selected ? <div className="absolute bottom-3 left-3 right-3 rounded-lg border border-white/15 bg-slate-950/90 p-3 text-xs text-slate-200"><strong>{team.lineup.players.find((player) => player.name === selected)?.name}</strong> · {team.lineup.players.find((player) => player.name === selected)?.position} · Hover para ver datos individuales mock</div> : null}</div></article>;
}

export default function MatchIntelligenceDemo() {
  const [now, setNow] = useState(0);
  const [mapMode, setMapMode] = useState('ATAQUES');
  const countdown = formatCountdown((new Date(mockMatch.kickoff).getTime() - now) / 1000);
  const kpiItems = useMemo(() => [
    ['Partidos', teams[0].kpis.partidos, teams[1].kpis.partidos], ['Victorias', teams[0].kpis.victorias, teams[1].kpis.victorias], ['Empates', teams[0].kpis.empates, teams[1].kpis.empates], ['Derrotas', teams[0].kpis.derrotas, teams[1].kpis.derrotas], ['Goles a favor', teams[0].kpis.golesFavor, teams[1].kpis.golesFavor], ['Goles recibidos', teams[0].kpis.golesRecibidos, teams[1].kpis.golesRecibidos], ['Diferencia de goles', teams[0].kpis.diferencia, teams[1].kpis.diferencia], ['Posesión', teams[0].kpis.posesion, teams[1].kpis.posesion], ['Tiros por partido', teams[0].kpis.tiros, teams[1].kpis.tiros], ['Tiros al arco', teams[0].kpis.tirosArco, teams[1].kpis.tirosArco], ['Corners', teams[0].kpis.corners, teams[1].kpis.corners], ['Tarjetas', teams[0].kpis.tarjetas, teams[1].kpis.tarjetas],
  ] as Array<[string, number, number]>, []);
  useEffect(() => { startTransition(() => setNow(Date.now())); const timer = window.setInterval(() => startTransition(() => setNow(Date.now())), 1000); return () => window.clearInterval(timer); }, []);

  return <main className="min-h-screen bg-[#03070d] text-white"><div className="border-b border-white/10 bg-[#050b14]/90"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 md:px-8"><Link href="/" className="text-xl font-black tracking-tight">SPORTIVA<span className="text-cyan-300">24</span></Link><span className="hidden text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500 md:block">Match Intelligence Center</span><Link href="/futbol" className="text-xs font-semibold text-slate-300 hover:text-white">Fútbol</Link></div></div>
    <div className="mx-auto max-w-7xl px-4 pb-16 pt-8 md:px-8 md:pt-12">
      <header className="relative overflow-hidden rounded-[28px] border border-cyan-300/15 bg-[radial-gradient(circle_at_50%_0%,rgba(34,211,238,0.14),transparent_42%),linear-gradient(145deg,#0b1724,#050a13)] p-5 md:p-9"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-cyan-300">{mockMatch.competition} · {mockMatch.round}</p><p className="mt-2 text-sm text-slate-400">{mockMatch.kickoffLabel} · {mockMatch.venue}, {mockMatch.city}</p></div><span className="rounded-full border border-amber-300/30 bg-amber-300/10 px-3 py-1.5 text-[10px] font-bold tracking-[0.15em] text-amber-200">{mockMatch.status}</span></div><div className="mx-auto mt-9 grid max-w-4xl grid-cols-[1fr_auto_1fr] items-center gap-4 text-center md:gap-12"><div className="flex flex-col items-center"><Crest team={teams[0]} size="h-24 w-24 md:h-32 md:w-32" /><h1 className="mt-4 text-lg font-bold md:text-2xl">{teams[0].name}</h1><p className="mt-2 text-xs text-slate-400">{teams[0].position}º · {teams[0].points} pts</p></div><div><p className="font-editorial text-4xl text-white md:text-6xl">VS</p><p className="mt-3 text-xs font-bold uppercase tracking-[0.15em] text-slate-500">Previa</p></div><div className="flex flex-col items-center"><Crest team={teams[1]} size="h-24 w-24 md:h-32 md:w-32" /><h2 className="mt-4 text-lg font-bold md:text-2xl">{teams[1].name}</h2><p className="mt-2 text-xs text-slate-400">{teams[1].position}º · {teams[1].points} pts</p></div></div><div className="mt-9 border-t border-white/10 pt-5"><p className="text-center text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500">El partido comienza en</p><div className="mt-3 grid grid-cols-4 gap-2 md:mx-auto md:max-w-xl md:gap-5">{[['DÍAS', countdown.days], ['HORAS', countdown.hours], ['MIN', countdown.minutes], ['SEG', countdown.seconds]].map(([label, value]) => <div key={String(label)} className="text-center"><p className="font-mono text-2xl font-bold text-cyan-100 md:text-4xl">{String(value).padStart(2, '0')}</p><p className="mt-1 text-[9px] font-bold tracking-[0.16em] text-slate-500">{label}</p></div>)}</div></div></header>
      <nav className="sticky top-0 z-20 -mx-4 mt-5 overflow-x-auto border-y border-white/10 bg-[#050b14]/95 px-4 py-3 backdrop-blur md:mx-0 md:rounded-xl md:border md:px-5"><div className="flex min-w-max gap-5">{navItems.map((item) => <a key={item} href={`#${item.toLowerCase()}`} className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400 transition hover:text-cyan-200">{item}</a>)}</div></nav>
      <section id="resumen" className="mt-10"><SectionTitle eyebrow="Sportiva24 Match Intelligence" title="Una previa construida con contexto" /><div className="grid gap-5 lg:grid-cols-[1.25fr_0.75fr]"><article className="rounded-2xl border border-cyan-300/20 bg-[#07131f] p-5 md:p-7"><div className="grid gap-5 sm:grid-cols-3">{[['Atlético', mockMatch.model.home, 'text-cyan-200'], ['Empate', mockMatch.model.draw, 'text-amber-200'], ['Real Madrid', mockMatch.model.away, 'text-rose-200']].map(([label, value, color]) => <div key={String(label)} className="text-center"><p className="text-xs text-slate-400">{label}</p><p className={`mt-2 text-4xl font-black ${color}`}>{value}%</p><div className="mt-3 h-1.5 rounded-full bg-slate-800"><div className="h-full rounded-full bg-current opacity-80" style={{ width: `${value}%` }} /></div></div>)}</div><div className="mt-8 border-t border-white/10 pt-5"><div className="flex items-center justify-between text-sm"><span className="text-slate-300">Nivel de confianza del modelo</span><strong className="text-cyan-100">{mockMatch.confidence} / 100</strong></div><div className="mt-3 h-2 rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-300" style={{ width: `${mockMatch.confidence}%` }} /></div></div></article><article className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5 md:p-7"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500">Modelo Sportiva24</p><p className="mt-4 text-sm leading-7 text-slate-300">Estimación modelada para este demo. No representa certeza ni reemplaza el análisis del contexto.</p><div className="mt-5 grid grid-cols-3 gap-2 text-center text-xs"><div><p className="text-slate-500">xG ATL</p><strong className="text-white">{mockMatch.model.expectedGoals.home}</strong></div><div><p className="text-slate-500">xG total</p><strong className="text-white">{mockMatch.model.expectedGoals.total}</strong></div><div><p className="text-slate-500">xG RMA</p><strong className="text-white">{mockMatch.model.expectedGoals.away}</strong></div></div></article></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{mockMatch.factors.map((factor, index) => <article key={factor.label} className="rounded-xl border border-slate-800 bg-slate-950/60 p-4"><span className="font-mono text-xs text-cyan-300">0{index + 1}</span><h3 className="mt-3 text-sm font-semibold text-white">{factor.label}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{factor.note}</p><p className="mt-3 text-lg font-bold text-slate-200">{factor.score}<span className="text-xs text-slate-600">/100</span></p></article>)}</div></section>
      <section className="mt-16 rounded-2xl border border-amber-300/20 bg-[#11100b] p-5 md:p-8"><SectionTitle eyebrow="Lectura Sportiva24" title="El contexto detrás de los números" /><p className="max-w-4xl text-lg leading-8 text-slate-200">{mockMatch.reading}</p><div className="mt-8 grid gap-3 md:grid-cols-5">{mockMatch.keys.map(([number, title, text]) => <article key={number} className="border-t border-amber-300/30 pt-3"><span className="font-mono text-xs text-amber-300">{number}</span><h3 className="mt-3 text-sm font-semibold text-white">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></article>)}</div></section>
      <section id="estadísticas" className="mt-16"><SectionTitle eyebrow="Números clave" title="Comparativa de rendimiento" /><div className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5 md:p-8"><ComparativeBars keys={['ATLÉTICO', 'REAL MADRID']} items={kpiItems.map(([label, home, away]) => ({ label, values: [home, away] as [number, number], suffix: ['Posesión'].includes(label) ? '%' : '' }))} /></div></section>
      <section className="mt-16"><SectionTitle eyebrow="Forma reciente" title="La secuencia que trae cada equipo" /><div className="grid gap-5 md:grid-cols-2"><FormPanel team={teams[0]} /><FormPanel team={teams[1]} /></div></section>
      <section className="mt-16 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5 md:p-7"><SectionTitle eyebrow="Ataque" title="Rendimiento ofensivo" /><ComparativeBars keys={['ATLÉTICO', 'REAL MADRID']} items={metricItems('attack', [['Goles', 'goles'], ['xG', 'xg'], ['Tiros', 'tiros'], ['Tiros al arco', 'tirosArco'], ['Grandes ocasiones', 'ocasiones'], ['Conversión', 'conversion', '%'], ['Ataques peligrosos', 'ataques'], ['Pases clave', 'pasesClave']])} /></article><article className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5 md:p-7"><SectionTitle eyebrow="Defensa" title="Rendimiento defensivo" /><ComparativeBars keys={['ATLÉTICO', 'REAL MADRID']} items={metricItems('defense', [['Goles recibidos', 'goles'], ['xGA', 'xga'], ['Porterías a cero', 'porteriasCero'], ['Recuperaciones', 'recuperaciones'], ['Entradas', 'entradas'], ['Intercepciones', 'intercepciones'], ['Despejes', 'despejes'], ['Errores que terminan en tiro', 'erroresTiro'], ['Errores que terminan en gol', 'erroresGol']])} /></article></section>
      <section className="mt-16 grid gap-5 lg:grid-cols-3"><article className="photo-panel rounded-2xl p-5"><div className="relative z-10"><SectionTitle eyebrow="Disciplina" title="Tarjetas y faltas" /><ComparativeBars keys={['ATLÉTICO', 'REAL MADRID']} items={metricItems('defense', [['Tarjetas', 'tarjetas'], ['Faltas', 'faltas']])} /></div></article></section>
      <section id="alineaciones" className="mt-16"><SectionTitle eyebrow="Alineaciones probables" title="El partido sobre el campo" /><div className="mb-5 rounded-xl border border-amber-300/20 bg-amber-300/5 px-4 py-3 text-sm text-amber-100">Estas alineaciones son mock de demostración y deben confirmarse antes del partido.</div><div className="grid gap-5 lg:grid-cols-2"><Lineup team={teams[0]} /><Lineup team={teams[1]} /></div></section>
      <section className="mt-16"><SectionTitle eyebrow="Duelos a seguir" title="Emparejamientos que pueden explicar el partido" /><div className="grid gap-3 sm:grid-cols-2">{[['Vinícius Jr.', 'Lateral Atlético', 'Velocidad, uno contra uno y espacio a la espalda.'], ['Mbappé', 'Centrales Atlético', 'Movilidad entre líneas y ataques al espacio.'], ['Bellingham', 'Mediocampo Atlético', 'Llegadas desde segunda línea y presión tras pérdida.'], ['Julián Álvarez', 'Centrales Real Madrid', 'Movilidad, apoyos y definición en el área.']].map(([left, right, text]) => <article key={left} className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5"><div className="flex items-center justify-between gap-3 text-sm font-bold"><span className="text-cyan-200">{left}</span><span className="text-slate-600">VS</span><span className="text-amber-200">{right}</span></div><p className="mt-4 text-sm leading-6 text-slate-400">{text}</p></article>)}</div></section>
      <section id="táctica" className="mt-16"><SectionTitle eyebrow="Análisis táctico" title="Tres lecturas del plan de juego" /><div className="grid gap-4 md:grid-cols-3">{[['Atlético con balón', 'Salida con amplitud, progresión por fuera y ataques rápidos después de recuperar.'], ['Real Madrid con balón', 'Posesión con cambios de orientación y libertad para sus jugadores ofensivos.'], ['Transiciones', 'El equipo que proteja mejor la pérdida puede controlar los momentos de mayor aceleración.']].map(([title, text]) => <article key={title} className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5"><h3 className="text-lg font-semibold text-white">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-400">{text}</p><div className="mt-5 flex items-center gap-2 text-xs font-bold text-cyan-200"><span>ATAQUE</span><span className="text-slate-600">→</span><span>OCASIÓN</span></div></article>)}</div></section>
      <section className="mt-16"><SectionTitle eyebrow="Mapa de zonas" title="Actividad modelada del campo" /><div className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5 md:p-7"><div className="flex gap-2 overflow-x-auto pb-5">{['ATAQUES', 'TIROS', 'RECUPERACIONES', 'PROGRESIONES'].map((mode) => <button key={mode} type="button" onClick={() => setMapMode(mode)} className={`shrink-0 rounded-full border px-4 py-2 text-[10px] font-bold tracking-[0.12em] ${mapMode === mode ? 'border-cyan-300 bg-cyan-300/10 text-cyan-100' : 'border-slate-700 text-slate-500'}`}>{mode}</button>)}</div><div className="relative mx-auto aspect-[2/1] max-w-3xl overflow-hidden rounded-xl border border-emerald-300/20 bg-[#123b32]"><div className="absolute inset-4 rounded-lg border border-white/20" /><div className="absolute left-1/2 top-1/2 h-px w-[calc(100%-2rem)] -translate-x-1/2 bg-white/15" />{[18, 31, 44, 57, 70, 83].map((left, index) => <span key={left} className="absolute h-5 w-5 rounded-full bg-cyan-300/70 shadow-[0_0_24px_rgba(103,232,249,0.7)]" style={{ left: `${left}%`, top: `${28 + ((index * 17) % 45)}%` }} />)}<p className="absolute bottom-3 left-3 rounded bg-slate-950/70 px-2 py-1 text-[10px] font-bold text-white">{mapMode} · MOCK DATA</p></div></div></section>
      <section id="h2h" className="mt-16"><SectionTitle eyebrow="Head to head" title="Últimos enfrentamientos" /><div className="overflow-x-auto rounded-2xl border border-slate-800 bg-slate-950/70"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-slate-800 text-[10px] uppercase tracking-[0.15em] text-slate-500"><tr><th className="px-5 py-4">Fecha</th><th className="px-5 py-4">Competición</th><th className="px-5 py-4">Local</th><th className="px-5 py-4">Resultado</th><th className="px-5 py-4">Visitante</th></tr></thead><tbody>{mockMatch.h2h.map((row) => <tr key={row.join('-')} className="border-b border-slate-800/70 last:border-0"><td className="px-5 py-4 text-slate-500">{row[0]}</td><td className="px-5 py-4 text-slate-400">{row[1]}</td><td className="px-5 py-4 text-slate-200">{row[2]}</td><td className="px-5 py-4 font-bold text-white">{row[3]}</td><td className="px-5 py-4 text-slate-200">{row[4]}</td></tr>)}</tbody></table></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-800 bg-slate-950/70 p-4 text-center"><p className="text-xs text-slate-500">Victorias Atlético</p><strong className="mt-2 block text-2xl text-cyan-200">2</strong></div><div className="rounded-xl border border-slate-800 bg-slate-950/70 p-4 text-center"><p className="text-xs text-slate-500">Empates</p><strong className="mt-2 block text-2xl text-white">0</strong></div><div className="rounded-xl border border-slate-800 bg-slate-950/70 p-4 text-center"><p className="text-xs text-slate-500">Victorias Real Madrid</p><strong className="mt-2 block text-2xl text-amber-200">3</strong></div></div></section>
      <section id="contexto" className="mt-16 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5 md:p-7"><SectionTitle eyebrow="Contexto LaLiga" title="Tabla de posiciones" /><div className="space-y-2">{mockMatch.league.map((row) => <div key={row[0]} className={`grid grid-cols-[2rem_1fr_3rem_4rem] items-center rounded-lg px-3 py-3 text-sm ${row[0].includes('Real') || row[0].includes('Atlético') ? 'border border-cyan-300/20 bg-cyan-300/5' : 'bg-black/20'}`}><span className="text-slate-500">{row[1]}</span><span className="font-semibold text-white">{row[0]}</span><span className="text-right text-slate-300">{row[2]} pts</span><span className="text-right text-cyan-200">DG {row[4]}</span></div>)}</div></article><div className="space-y-5"><article className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5"><SectionTitle eyebrow="Entrenadores" title="El banquillo también decide" />{mockMatch.coaches.map((coach) => <div key={coach.team} className="flex items-center justify-between border-b border-slate-800 py-3 last:border-0"><div><p className="font-semibold text-white">{coach.name}</p><p className="text-xs text-slate-500">{coach.team} · {coach.formation}</p></div><span className="text-xs text-slate-400">{coach.matches} partidos</span></div>)}</article><article className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5"><SectionTitle eyebrow="Árbitro" title={mockMatch.referee.name} /><div className="grid grid-cols-2 gap-3 text-sm text-slate-300"><span>{mockMatch.referee.matches} partidos dirigidos</span><span>{mockMatch.referee.cards} tarjetas / partido</span><span>{mockMatch.referee.fouls} faltas / partido</span><span>{mockMatch.referee.penalties} penales · {mockMatch.referee.reds} rojas</span></div></article></div></section>
      <section className="mt-16 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5 md:p-7"><SectionTitle eyebrow="Contexto del partido" title={mockMatch.venue} /><div className="grid grid-cols-2 gap-4 text-sm"><div><p className="text-xs text-slate-500">Ciudad</p><p className="mt-1 text-white">{mockMatch.city}</p></div><div><p className="text-xs text-slate-500">Capacidad</p><p className="mt-1 text-white">{mockMatch.venue.capacity}</p></div><div><p className="text-xs text-slate-500">Superficie</p><p className="mt-1 text-white">{mockMatch.venue.surface}</p></div><div><p className="text-xs text-slate-500">Condiciones</p><p className="mt-1 text-slate-400">Sin información</p></div></div></article><article className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5 md:p-7"><SectionTitle eyebrow="Distribución modelada de goles" title="Modelo Sportiva24" /><div className="flex items-end justify-between gap-2">{[19, 27, 25, 16, 8, 5].map((value, index) => <div key={index} className="flex flex-1 flex-col items-center gap-2"><span className="text-xs text-slate-400">{value}%</span><div className="w-full rounded-t bg-cyan-300" style={{ height: `${value * 3}px` }} /><span className="text-[10px] text-slate-500">{index === 5 ? '5+' : index}</span></div>)}</div><div className="mt-5 grid grid-cols-3 gap-2 border-t border-slate-800 pt-4 text-center text-xs"><div><p className="text-slate-500">Atlético</p><strong className="text-white">1.42</strong></div><div><p className="text-slate-500">Total</p><strong className="text-white">2.93</strong></div><div><p className="text-slate-500">Real Madrid</p><strong className="text-white">1.51</strong></div></div></article></section>
      <section className="mt-16"><SectionTitle eyebrow="Posibles escenarios" title="Lecturas abiertas del partido" /><div className="grid gap-4 md:grid-cols-3">{mockMatch.scenarios.map(([label, title, text]) => <article key={label} className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5"><p className="font-mono text-xs text-cyan-300">{label}</p><h3 className="mt-3 text-lg font-semibold text-white">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-400">{text}</p></article>)}</div></section>
      <section className="mt-16 grid gap-5 md:grid-cols-2"><article className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5 md:p-7"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-cyan-300">Información en tiempo real</p><h2 className="mt-2 text-2xl font-semibold text-white">Disponible durante el partido</h2><p className="mt-3 text-sm leading-7 text-slate-400">Este módulo queda preparado para marcador, minuto, posesión, tiros, corners, tarjetas, sustituciones, eventos y momentum cuando el estado cambie a EN VIVO.</p><span className="mt-5 inline-flex rounded-full border border-slate-700 px-3 py-1 text-xs text-slate-400">Estado actual: PREVIA</span></article><article className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5 md:p-7"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500">Post-partido</p><h2 className="mt-2 text-2xl font-semibold text-white">Análisis posterior</h2><p className="mt-3 text-sm leading-7 text-slate-400">Después del encuentro podrán incorporarse resultado, estadísticas, xG, ocasiones, jugador destacado, momentos clave y la comparación Modelo vs Realidad.</p><span className="mt-5 inline-flex rounded-full border border-slate-700 px-3 py-1 text-xs text-slate-500">Disponible después del partido</span></article></section>
    </div><footer className="border-t border-white/10 px-4 py-8 text-center text-xs text-slate-600">Sportiva24 Match Intelligence · Demo con datos mock deterministas</footer></main>;
}
